//
// Copyright (C) 2026 Emulation Server Project
//
// This program is free software. You can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation. either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY. Without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

namespace EmulationServer.WorldServer.Networking.Packets;

public enum WorldOpcode : ushort
{
    CMSG_CHAR_CREATE = 0x036,
    CMSG_CHAR_ENUM = 0x037,
    CMSG_CHAR_DELETE = 0x038,
    SMSG_CHAR_CREATE = 0x03A,
    SMSG_CHAR_ENUM = 0x03B,
    SMSG_CHAR_DELETE = 0x03C,
    CMSG_PLAYER_LOGIN = 0x03D,
    SMSG_NEW_WORLD = 0x03E,
    SMSG_TRANSFER_PENDING = 0x03F,
    SMSG_TRANSFER_ABORTED = 0x040,
    SMSG_CHARACTER_LOGIN_FAILED = 0x041,
    SMSG_LOGIN_SETTIMESPEED = 0x042,
    CMSG_SERVERTIME = 0x048,
    SMSG_SERVERTIME = 0x049,
    CMSG_PLAYER_LOGOUT = 0x04A,
    CMSG_LOGOUT_REQUEST = 0x04B,
    SMSG_LOGOUT_RESPONSE = 0x04C,
    SMSG_LOGOUT_COMPLETE = 0x04D,
    CMSG_LOGOUT_CANCEL = 0x04E,
    SMSG_LOGOUT_CANCEL_ACK = 0x04F,
    CMSG_NAME_QUERY = 0x050,
    SMSG_NAME_QUERY_RESPONSE = 0x051,
    CMSG_ITEM_QUERY_SINGLE = 0x056,
    SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x058,
    CMSG_WHO = 0x062,
    SMSG_WHO = 0x063,
    CMSG_MESSAGECHAT = 0x095,
    SMSG_MESSAGECHAT = 0x096,
    CMSG_JOIN_CHANNEL = 0x097,
    CMSG_LEAVE_CHANNEL = 0x098,
    SMSG_CHANNEL_NOTIFY = 0x099,
    CMSG_CHANNEL_LIST = 0x09A,
    SMSG_CHANNEL_LIST = 0x09B,
    CMSG_CHANNEL_PASSWORD = 0x09C,
    SMSG_UPDATE_OBJECT = 0x0A9,
    SMSG_DESTROY_OBJECT = 0x0AA,
    CMSG_OPENING_CINEMATIC = 0x0F9,
    CMSG_NEXT_CINEMATIC_CAMERA = 0x0FB,
    CMSG_COMPLETE_CINEMATIC = 0x0FC,
    SMSG_TUTORIAL_FLAGS = 0x0FD,
    CMSG_TUTORIAL_FLAG = 0x0FE,
    CMSG_TUTORIAL_CLEAR = 0x0FF,
    CMSG_TUTORIAL_RESET = 0x100,
    CMSG_STANDSTATECHANGE = 0x101,
    SMSG_INITIALIZE_FACTIONS = 0x122,
    CMSG_SET_ACTION_BUTTON = 0x128,
    SMSG_ACTION_BUTTONS = 0x129,
    SMSG_INITIAL_SPELLS = 0x12A,
    SMSG_BINDPOINTUPDATE = 0x155,
    SMSG_NOTIFICATION = 0x1CB,
    CMSG_PLAYED_TIME = 0x1CC,
    SMSG_PLAYED_TIME = 0x1CD,
    CMSG_QUERY_TIME = 0x1CE,
    SMSG_QUERY_TIME_RESPONSE = 0x1CF,
    CMSG_PING = 0x1DC,
    SMSG_PONG = 0x1DD,
    CMSG_ZONEUPDATE = 0x1F4,
    SMSG_AUTH_CHALLENGE = 0x1EC,
    CMSG_AUTH_SESSION = 0x1ED,
    SMSG_AUTH_RESPONSE = 0x1EE,
    SMSG_ACCOUNT_DATA_TIMES = 0x209,
    CMSG_REQUEST_ACCOUNT_DATA = 0x20A,
    CMSG_UPDATE_ACCOUNT_DATA = 0x20B,
    SMSG_UPDATE_ACCOUNT_DATA = 0x20C,
    SMSG_SET_REST_START = 0x21E,
    SMSG_LOGIN_VERIFY_WORLD = 0x236,
    CMSG_SET_ACTIONBAR_TOGGLES = 0x2BF,
    CMSG_ITEM_NAME_QUERY = 0x2C4,
    SMSG_ITEM_NAME_QUERY_RESPONSE = 0x2C5,
    SMSG_ADDON_INFO = 0x2EF,
    SMSG_MOTD = 0x33D,
}
