//
// Copyright (C) 2026 Emulation Server Project
//
// This program is free software. You can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation. either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY. Without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

using System.Globalization;
using EmulationServer.Shared.Data.MapStore;

namespace EmulationServer.Tools.Extraction.Validation;

/**
  * Verifies and summarizes every mapstore .bin file type generated by the extraction tool.
  */
public sealed class MapStoreBinVerifier
{
    /**
      * Verifies one mapstore .bin file and returns a readable payload summary.
      */
    public MapStoreBinValidationResult VerifyFile(string path, bool detailed)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        List<string> summaryLines = [];
        List<ValidationMessage> messages = [];

        try
        {
            if (!File.Exists(path))
            {
                throw new FileNotFoundException("Mapstore .bin file was not found.", path);
            }

            string fileName = Path.GetFileName(path);
            if (string.Equals(fileName, MapStoreFileNames.IndexFileName, StringComparison.OrdinalIgnoreCase))
            {
                VerifyIndexFile(path, summaryLines, messages, detailed);
                if (messages.Count == 0)
                {
                    messages.Add(new ValidationMessage(ValidationSeverity.Info, $"{path}: mapstore .bin verification passed."));
                }

                return new MapStoreBinValidationResult(path, summaryLines, messages);
            }

            MapStoreDataKind expectedKind = ResolveExpectedKind(path);
            MapStoreFile file = MapStoreBinary.ReadFile(path, expectedKind);

            AddOuterHeaderSummary(file, summaryLines);
            ValidateCanonicalPath(file, messages);
            VerifyTilePayload(file, summaryLines, messages, detailed);
        }
        catch (Exception exception) when (exception is IOException or InvalidDataException or ArgumentException or EndOfStreamException or OverflowException)
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Error, $"{path}: {exception.Message}"));
        }

        if (messages.Count == 0)
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Info, $"{path}: mapstore .bin verification passed."));
        }

        return new MapStoreBinValidationResult(path, summaryLines, messages);
    }

    /**
      * Verifies one map.index.bin file.
      */
    private static void VerifyIndexFile(string path, List<string> summaryLines, List<ValidationMessage> messages, bool detailed)
    {
        using FileStream stream = File.OpenRead(path);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(magic, MapStoreFormat.IndexMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{path} has invalid mapstore index magic '{magic}'. Expected '{MapStoreFormat.IndexMagic}'.");
        }

        ushort version = reader.ReadUInt16();
        ushort build = reader.ReadUInt16();
        uint mapId = reader.ReadUInt32();
        int recordCount = reader.ReadInt32();

        if (version != MapStoreFormat.CurrentVersion)
        {
            throw new InvalidDataException($"{path} has unsupported mapstore index version {version}. Expected {MapStoreFormat.CurrentVersion}.");
        }

        if (recordCount < 0)
        {
            throw new InvalidDataException($"{path} has invalid negative mapstore tile count {recordCount}.");
        }

        int terrainTiles = 0;
        int liquidTiles = 0;
        int collisionTiles = 0;
        int navmeshTiles = 0;
        List<string> tileLines = [];

        for (int index = 0; index < recordCount; index++)
        {
            byte tileX = reader.ReadByte();
            byte tileY = reader.ReadByte();
            MapStoreTileDataFlags flags = (MapStoreTileDataFlags)reader.ReadByte();
            _ = reader.ReadByte();

            if ((flags & MapStoreTileDataFlags.Terrain) != 0)
            {
                terrainTiles++;
            }

            if ((flags & MapStoreTileDataFlags.Liquid) != 0)
            {
                liquidTiles++;
            }

            if ((flags & MapStoreTileDataFlags.Collision) != 0)
            {
                collisionTiles++;
            }

            if ((flags & MapStoreTileDataFlags.Navmesh) != 0)
            {
                navmeshTiles++;
            }

            if (detailed)
            {
                tileLines.Add($"  Tile: {MapStoreFileNames.FormatTileKey(mapId, tileX, tileY)} flags={flags}");
            }
        }

        if (stream.Position != stream.Length)
        {
            throw new InvalidDataException($"{path} contains trailing bytes after the mapstore index records.");
        }

        string? mapDirectoryName = Directory.GetParent(path)?.Name;
        if (mapDirectoryName is not null && MapStoreFileNames.TryParseMapDirectoryName(mapDirectoryName, out uint directoryMapId) && directoryMapId != mapId)
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Error, $"{path}: directory map id {MapStoreFileNames.FormatMapId(directoryMapId)} does not match index map id {MapStoreFileNames.FormatMapId(mapId)}."));
        }

        summaryLines.Add($"File: {path}");
        summaryLines.Add("Kind: Index");
        summaryLines.Add($"Magic: {magic}");
        summaryLines.Add($"Version: {version}");
        summaryLines.Add($"Build: {build}");
        summaryLines.Add($"Map: {MapStoreFileNames.FormatMapId(mapId)}");
        summaryLines.Add($"Records: {recordCount}");
        summaryLines.Add($"Terrain tiles: {terrainTiles}");
        summaryLines.Add($"Liquid tiles: {liquidTiles}");
        summaryLines.Add($"Collision tiles: {collisionTiles}");
        summaryLines.Add($"Navmesh tiles: {navmeshTiles}");

        summaryLines.AddRange(tileLines);
    }

    /**
      * Resolves the expected tile file type from the canonical filename or the file magic.
      */
    private static MapStoreDataKind ResolveExpectedKind(string path)
    {
        string fileName = Path.GetFileName(path);
        if (MapStoreFileNames.TryParseTileFileName(fileName, out _, out _, out MapStoreDataKind kind))
        {
            return kind;
        }

        using FileStream stream = File.OpenRead(path);
        using BinaryReader reader = new(stream);
        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        return magic switch
        {
            MapStoreFormat.TerrainMagic => MapStoreDataKind.Terrain,
            MapStoreFormat.LiquidMagic => MapStoreDataKind.Liquid,
            MapStoreFormat.CollisionMagic => MapStoreDataKind.Collision,
            MapStoreFormat.NavmeshMagic => MapStoreDataKind.Navmesh,
            _ => throw new InvalidDataException($"{path} has unknown mapstore .bin magic '{magic}'."),
        };
    }

    /**
      * Adds the shared outer mapstore header fields to the summary.
      */
    private static void AddOuterHeaderSummary(MapStoreFile file, List<string> summaryLines)
    {
        summaryLines.Add($"File: {file.Path}");
        summaryLines.Add($"Kind: {file.Header.Kind}");
        summaryLines.Add($"Magic: {file.Header.Magic}");
        summaryLines.Add($"Version: {file.Header.Version}");
        summaryLines.Add($"Build: {file.Header.Build}");
        summaryLines.Add($"Map: {MapStoreFileNames.FormatMapId(file.Header.MapId)}");
        summaryLines.Add($"Tile: {MapStoreFileNames.FormatTileCoordinate(file.Header.TileX)}_{MapStoreFileNames.FormatTileCoordinate(file.Header.TileY)}");
        summaryLines.Add($"Payload bytes: {file.Header.PayloadSize}");
        summaryLines.Add($"Payload CRC32: 0x{file.Header.PayloadCrc32:X8}");
    }

    /**
      * Validates that the folder and filename match the ids stored inside the outer file header.
      */
    private static void ValidateCanonicalPath(MapStoreFile file, List<ValidationMessage> messages)
    {
        string fileName = Path.GetFileName(file.Path);
        if (!MapStoreFileNames.TryParseTileFileName(fileName, out byte fileTileX, out byte fileTileY, out MapStoreDataKind fileKind))
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Warning, $"{file.Path}: filename is not canonical mapstore tile format."));
            return;
        }

        if (fileTileX != file.Header.TileX || fileTileY != file.Header.TileY || fileKind != file.Header.Kind)
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Error, $"{file.Path}: filename does not match header tile/kind values."));
        }

        DirectoryInfo? tilesDirectory = Directory.GetParent(file.Path);
        string? mapDirectory = tilesDirectory?.Parent?.Name;
        if (mapDirectory is not null && MapStoreFileNames.TryParseMapDirectoryName(mapDirectory, out uint directoryMapId) && directoryMapId != file.Header.MapId)
        {
            messages.Add(new ValidationMessage(ValidationSeverity.Error, $"{file.Path}: directory map id {MapStoreFileNames.FormatMapId(directoryMapId)} does not match header map id {MapStoreFileNames.FormatMapId(file.Header.MapId)}."));
        }
    }

    /**
      * Dispatches payload verification to the concrete payload reader.
      */
    private static void VerifyTilePayload(MapStoreFile file, List<string> summaryLines, List<ValidationMessage> messages, bool detailed)
    {
        switch (file.Header.Kind)
        {
            case MapStoreDataKind.Terrain:
                VerifyTerrainPayload(file, summaryLines, detailed);
                break;

            case MapStoreDataKind.Liquid:
                VerifyLiquidPayload(file, summaryLines, detailed);
                break;

            case MapStoreDataKind.Collision:
                VerifyCollisionPayload(file, summaryLines, detailed);
                break;

            case MapStoreDataKind.Navmesh:
                VerifyNavmeshPayload(file, summaryLines);
                break;

            default:
                messages.Add(new ValidationMessage(ValidationSeverity.Error, $"{file.Path}: unknown mapstore payload kind {file.Header.Kind}."));
                break;
        }
    }

    /**
      * Verifies and summarizes terrain payload data.
      */
    private static void VerifyTerrainPayload(MapStoreFile file, List<string> summaryLines, bool detailed)
    {
        using MemoryStream stream = new(file.Payload, writable: false);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(magic, MapStorePayloadConstants.TerrainMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file.Path} has invalid terrain payload magic '{magic}'. Expected '{MapStorePayloadConstants.TerrainMagic}'.");
        }

        uint areaSize = reader.ReadUInt32();
        uint heightSize = reader.ReadUInt32();
        uint holesSize = reader.ReadUInt32();
        long expectedPayloadSize = 16L + areaSize + heightSize + holesSize;
        if (expectedPayloadSize != file.Payload.Length)
        {
            throw new InvalidDataException($"{file.Path} has invalid terrain payload size. Header declares {expectedPayloadSize} byte(s), payload contains {file.Payload.Length} byte(s)." );
        }

        byte[] areaBytes = reader.ReadBytes(checked((int)areaSize));
        byte[] heightBytes = reader.ReadBytes(checked((int)heightSize));
        byte[] holesBytes = reader.ReadBytes(checked((int)holesSize));

        TerrainAreaSummary area = ReadAreaSummary(file.Path, areaBytes, detailed);
        TerrainHeightSummary height = ReadHeightSummary(file.Path, heightBytes, detailed);
        TerrainHolesSummary holes = ReadHolesSummary(file.Path, holesBytes);

        summaryLines.Add($"Payload magic: {magic}");
        summaryLines.Add($"Area section bytes: {areaSize}");
        summaryLines.Add($"Height section bytes: {heightSize}");
        summaryLines.Add($"Holes section bytes: {holesSize}");
        summaryLines.Add($"Area flags: 0x{area.Flags:X4}");
        summaryLines.Add($"Grid area flag: {area.GridAreaFlag}");
        summaryLines.Add($"Area grid present: {area.HasAreaGrid}");
        summaryLines.Add($"Unique area values: {area.UniqueAreaCount}");
        summaryLines.Add($"Height flags: 0x{height.Flags:X8}");
        summaryLines.Add($"Grid height: {height.GridHeight.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"Grid max height: {height.GridMaxHeight.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"V9 height grid present: {height.HasV9Grid}");
        summaryLines.Add($"V8 height grid present: {height.HasV8Grid}");
        summaryLines.Add($"Height minimum: {height.MinHeight.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"Height maximum: {height.MaxHeight.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"Non-empty hole cells: {holes.NonEmptyHoleCells}");

        if (detailed && area.SampleValues.Count > 0)
        {
            summaryLines.Add("Area samples: " + string.Join(", ", area.SampleValues));
        }
    }

    /**
      * Verifies and summarizes liquid payload data.
      */
    private static void VerifyLiquidPayload(MapStoreFile file, List<string> summaryLines, bool detailed)
    {
        using MemoryStream stream = new(file.Payload, writable: false);
        using BinaryReader reader = new(stream);

        string payloadMagic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(payloadMagic, MapStorePayloadConstants.LiquidPayloadMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file.Path} has invalid liquid payload magic '{payloadMagic}'. Expected '{MapStorePayloadConstants.LiquidPayloadMagic}'.");
        }

        uint liquidSectionSize = reader.ReadUInt32();
        if (8L + liquidSectionSize != file.Payload.Length)
        {
            throw new InvalidDataException($"{file.Path} has invalid liquid payload size. Header declares {liquidSectionSize} byte(s), payload contains {file.Payload.Length} byte(s)." );
        }

        summaryLines.Add($"Payload magic: {payloadMagic}");
        summaryLines.Add($"Liquid section bytes: {liquidSectionSize}");

        if (liquidSectionSize == 0)
        {
            summaryLines.Add("Has liquid: False");
            return;
        }

        string sectionMagic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(sectionMagic, MapStorePayloadConstants.LiquidSectionMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file.Path} has invalid liquid section magic '{sectionMagic}'. Expected '{MapStorePayloadConstants.LiquidSectionMagic}'.");
        }

        ushort flags = reader.ReadUInt16();
        ushort liquidTypeId = reader.ReadUInt16();
        byte offsetX = reader.ReadByte();
        byte offsetY = reader.ReadByte();
        byte width = reader.ReadByte();
        byte height = reader.ReadByte();
        float liquidLevel = reader.ReadSingle();

        int uniqueLiquidTypes = 0;
        int liquidFlagCells = 0;
        List<ushort> liquidTypeSamples = [];
        if ((flags & MapStorePayloadConstants.MapLiquidNoType) == 0)
        {
            HashSet<ushort> typeIds = [];
            for (int i = 0; i < MapStorePayloadConstants.AreaCellCount; i++)
            {
                ushort value = reader.ReadUInt16();
                typeIds.Add(value);
                if (liquidTypeSamples.Count < 8 && !liquidTypeSamples.Contains(value))
                {
                    liquidTypeSamples.Add(value);
                }
            }

            uniqueLiquidTypes = typeIds.Count;

            for (int i = 0; i < MapStorePayloadConstants.AreaCellCount; i++)
            {
                if (reader.ReadByte() != 0)
                {
                    liquidFlagCells++;
                }
            }
        }

        int liquidHeightSamples = 0;
        float minLiquidHeight = liquidLevel;
        float maxLiquidHeight = liquidLevel;
        if ((flags & MapStorePayloadConstants.MapLiquidNoHeight) == 0)
        {
            liquidHeightSamples = checked(width * height);
            if (liquidHeightSamples > 0)
            {
                minLiquidHeight = float.MaxValue;
                maxLiquidHeight = float.MinValue;
            }

            for (int i = 0; i < liquidHeightSamples; i++)
            {
                float value = reader.ReadSingle();
                minLiquidHeight = Math.Min(minLiquidHeight, value);
                maxLiquidHeight = Math.Max(maxLiquidHeight, value);
            }
        }

        if (stream.Position != stream.Length)
        {
            throw new InvalidDataException($"{file.Path} has {stream.Length - stream.Position} unread liquid payload byte(s).");
        }

        summaryLines.Add("Has liquid: True");
        summaryLines.Add($"Section magic: {sectionMagic}");
        summaryLines.Add($"Flags: 0x{flags:X4}");
        summaryLines.Add($"Liquid type id: {liquidTypeId}");
        summaryLines.Add($"Offset: {offsetX}_{offsetY}");
        summaryLines.Add($"Size: {width}x{height}");
        summaryLines.Add($"Liquid level: {liquidLevel.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"Type grid present: {(flags & MapStorePayloadConstants.MapLiquidNoType) == 0}");
        summaryLines.Add($"Unique liquid type values: {uniqueLiquidTypes}");
        summaryLines.Add($"Non-zero liquid flag cells: {liquidFlagCells}");
        summaryLines.Add($"Height grid present: {(flags & MapStorePayloadConstants.MapLiquidNoHeight) == 0}");
        summaryLines.Add($"Liquid height samples: {liquidHeightSamples}");
        summaryLines.Add($"Liquid height minimum: {minLiquidHeight.ToString("0.000", CultureInfo.InvariantCulture)}");
        summaryLines.Add($"Liquid height maximum: {maxLiquidHeight.ToString("0.000", CultureInfo.InvariantCulture)}");

        if (detailed && liquidTypeSamples.Count > 0)
        {
            summaryLines.Add("Liquid type samples: " + string.Join(", ", liquidTypeSamples));
        }
    }

    /**
      * Verifies and summarizes collision payload data.
      */
    private static void VerifyCollisionPayload(MapStoreFile file, List<string> summaryLines, bool detailed)
    {
        using MemoryStream stream = new(file.Payload, writable: false);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadAscii(reader, MapStorePayloadConstants.CollisionPayloadMagic.Length, "collision payload magic value");
        if (!string.Equals(magic, MapStorePayloadConstants.CollisionPayloadMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file.Path} has invalid collision payload magic '{magic}'. Expected '{MapStorePayloadConstants.CollisionPayloadMagic}'.");
        }

        uint version = reader.ReadUInt32();
        ushort build = reader.ReadUInt16();
        uint mapId = reader.ReadUInt32();
        int tileX = reader.ReadInt32();
        int tileY = reader.ReadInt32();
        int placementCount = reader.ReadInt32();

        if (mapId != file.Header.MapId || tileX != file.Header.TileX || tileY != file.Header.TileY)
        {
            string expectedKey = MapStoreFileNames.FormatTileKey(file.Header.MapId, file.Header.TileX, file.Header.TileY);
            string actualKey = MapStoreFileNames.FormatTileKey(mapId, tileX, tileY);
            throw new InvalidDataException($"{file.Path} has mismatched inner collision key. Expected {expectedKey}, got {actualKey}.");
        }

        if (build != file.Header.Build)
        {
            throw new InvalidDataException($"{file.Path} has mismatched inner collision build. Outer={file.Header.Build}, Inner={build}.");
        }

        if (placementCount < 0)
        {
            throw new InvalidDataException($"{file.Path} has invalid negative collision placement count {placementCount}.");
        }

        HashSet<string> modelKeys = [];
        List<string> placementSamples = [];
        for (int i = 0; i < placementCount; i++)
        {
            string modelKey = MapStoreBinaryPrimitives.ReadUtf8String(reader, file.Path, "collision model key");
            string normalizedPath = MapStoreBinaryPrimitives.ReadUtf8String(reader, file.Path, "collision model path");
            uint uniqueId = reader.ReadUInt32();
            (float X, float Y, float Z) position = ReadVector(reader);
            _ = ReadVector(reader);
            _ = ReadVector(reader);
            _ = ReadVector(reader);
            uint flags = reader.ReadUInt32();
            ushort doodadSet = reader.ReadUInt16();
            ushort nameSet = reader.ReadUInt16();

            modelKeys.Add(modelKey);
            if (detailed && placementSamples.Count < 10)
            {
                placementSamples.Add($"  Placement: id={uniqueId} model={modelKey} path={normalizedPath} pos=({position.X.ToString("0.000", CultureInfo.InvariantCulture)}, {position.Y.ToString("0.000", CultureInfo.InvariantCulture)}, {position.Z.ToString("0.000", CultureInfo.InvariantCulture)}) flags=0x{flags:X8} doodadSet={doodadSet} nameSet={nameSet}");
            }
        }

        if (stream.Position != stream.Length)
        {
            throw new InvalidDataException($"{file.Path} has {stream.Length - stream.Position} unread collision payload byte(s).");
        }

        summaryLines.Add($"Payload magic: {magic}");
        summaryLines.Add($"Payload version: {version}");
        summaryLines.Add($"Inner build: {build}");
        summaryLines.Add($"Inner map: {MapStoreFileNames.FormatMapId(mapId)}");
        summaryLines.Add($"Inner tile: {MapStoreFileNames.FormatTileCoordinate(tileX)}_{MapStoreFileNames.FormatTileCoordinate(tileY)}");
        summaryLines.Add($"Placements: {placementCount}");
        summaryLines.Add($"Unique collision models: {modelKeys.Count}");
        summaryLines.AddRange(placementSamples);
    }

    /**
      * Verifies and summarizes navmesh placeholder payload data.
      */
    private static void VerifyNavmeshPayload(MapStoreFile file, List<string> summaryLines)
    {
        using MemoryStream stream = new(file.Payload, writable: false);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(magic, MapStorePayloadConstants.NavmeshPayloadMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file.Path} has invalid navmesh payload magic '{magic}'. Expected '{MapStorePayloadConstants.NavmeshPayloadMagic}'.");
        }

        uint polygonCount = reader.ReadUInt32();
        uint connectionCount = reader.ReadUInt32();
        if (stream.Position != stream.Length)
        {
            throw new InvalidDataException($"{file.Path} has {stream.Length - stream.Position} unread navmesh payload byte(s). The verifier currently expects the placeholder navmesh format.");
        }

        summaryLines.Add($"Payload magic: {magic}");
        summaryLines.Add($"Polygons: {polygonCount}");
        summaryLines.Add($"Connections: {connectionCount}");
        summaryLines.Add($"Placeholder: {polygonCount == 0 && connectionCount == 0}");
    }

    /**
      * Reads the terrain area summary.
      */
    private static TerrainAreaSummary ReadAreaSummary(string path, byte[] section, bool detailed)
    {
        if (section.Length < 8)
        {
            throw new InvalidDataException($"{path} has an invalid area section size of {section.Length} byte(s).");
        }

        using MemoryStream stream = new(section, writable: false);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(magic, MapStorePayloadConstants.AreaMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{path} has invalid area section magic '{magic}'. Expected '{MapStorePayloadConstants.AreaMagic}'.");
        }

        ushort flags = reader.ReadUInt16();
        ushort gridArea = reader.ReadUInt16();
        bool hasAreaGrid = (flags & MapStorePayloadConstants.MapAreaNoArea) == 0;
        HashSet<ushort> uniqueValues = [];
        List<ushort> sampleValues = [];

        if (!hasAreaGrid)
        {
            if (stream.Position != stream.Length)
            {
                throw new InvalidDataException($"{path} has extra bytes after constant area section data.");
            }

            uniqueValues.Add(gridArea);
            return new TerrainAreaSummary(flags, gridArea, false, uniqueValues.Count, sampleValues);
        }

        int expectedSize = 8 + MapStorePayloadConstants.AreaCellCount * sizeof(ushort);
        if (section.Length != expectedSize)
        {
            throw new InvalidDataException($"{path} has invalid area grid size. Expected {expectedSize} byte(s), got {section.Length} byte(s).");
        }

        for (int i = 0; i < MapStorePayloadConstants.AreaCellCount; i++)
        {
            ushort value = reader.ReadUInt16();
            uniqueValues.Add(value);
            if (detailed && sampleValues.Count < 8 && !sampleValues.Contains(value))
            {
                sampleValues.Add(value);
            }
        }

        return new TerrainAreaSummary(flags, gridArea, true, uniqueValues.Count, sampleValues);
    }

    /**
      * Reads the terrain height summary.
      */
    private static TerrainHeightSummary ReadHeightSummary(string path, byte[] section, bool detailed)
    {
        _ = detailed;

        if (section.Length < 16)
        {
            throw new InvalidDataException($"{path} has an invalid height section size of {section.Length} byte(s).");
        }

        using MemoryStream stream = new(section, writable: false);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadFourCC(reader);
        if (!string.Equals(magic, MapStorePayloadConstants.HeightMagic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{path} has invalid height section magic '{magic}'. Expected '{MapStorePayloadConstants.HeightMagic}'.");
        }

        uint flags = reader.ReadUInt32();
        float gridHeight = reader.ReadSingle();
        float gridMaxHeight = reader.ReadSingle();

        if ((flags & MapStorePayloadConstants.MapHeightNoHeight) != 0)
        {
            if (stream.Position != stream.Length)
            {
                throw new InvalidDataException($"{path} has extra bytes after constant height section data.");
            }

            return new TerrainHeightSummary(flags, gridHeight, gridMaxHeight, false, false, gridHeight, gridMaxHeight);
        }

        if ((flags & (MapStorePayloadConstants.MapHeightAsInt16 | MapStorePayloadConstants.MapHeightAsInt8)) != 0)
        {
            throw new InvalidDataException($"{path} uses compressed height flags 0x{flags:X8}, but the runtime verifier currently expects float height grids.");
        }

        const int expectedSize = 16 + ((MapStorePayloadConstants.V9VertexCount + MapStorePayloadConstants.V8VertexCount) * sizeof(float));
        if (section.Length != expectedSize)
        {
            throw new InvalidDataException($"{path} has invalid height grid size. Expected {expectedSize} byte(s), got {section.Length} byte(s).");
        }

        float minHeight = float.MaxValue;
        float maxHeight = float.MinValue;
        int samples = MapStorePayloadConstants.V9VertexCount + MapStorePayloadConstants.V8VertexCount;
        for (int i = 0; i < samples; i++)
        {
            float value = reader.ReadSingle();
            minHeight = Math.Min(minHeight, value);
            maxHeight = Math.Max(maxHeight, value);
        }

        return new TerrainHeightSummary(flags, gridHeight, gridMaxHeight, true, true, minHeight, maxHeight);
    }

    /**
      * Reads the terrain holes summary.
      */
    private static TerrainHolesSummary ReadHolesSummary(string path, byte[] section)
    {
        if (section.Length == 0)
        {
            return new TerrainHolesSummary(0);
        }

        int expectedSize = MapStorePayloadConstants.AreaCellCount * sizeof(ushort);
        if (section.Length != expectedSize)
        {
            throw new InvalidDataException($"{path} has invalid holes section size. Expected {expectedSize} byte(s), got {section.Length} byte(s).");
        }

        using MemoryStream stream = new(section, writable: false);
        using BinaryReader reader = new(stream);

        int nonEmptyCells = 0;
        for (int i = 0; i < MapStorePayloadConstants.AreaCellCount; i++)
        {
            if (reader.ReadUInt16() != 0)
            {
                nonEmptyCells++;
            }
        }

        return new TerrainHolesSummary(nonEmptyCells);
    }

    /**
      * Reads one collision vector.
      */
    private static (float X, float Y, float Z) ReadVector(BinaryReader reader)
    {
        return (reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private sealed record TerrainAreaSummary(ushort Flags, ushort GridAreaFlag, bool HasAreaGrid, int UniqueAreaCount, IReadOnlyList<ushort> SampleValues);
    private sealed record TerrainHeightSummary(uint Flags, float GridHeight, float GridMaxHeight, bool HasV9Grid, bool HasV8Grid, float MinHeight, float MaxHeight);
    private sealed record TerrainHolesSummary(int NonEmptyHoleCells);
}
