//
// Copyright (C) 2026 Emulation Server Project
//
// This program is free software. You can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation. either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY. Without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

using EmulationServer.Shared.Data.MapStore;
using MapStoreViewer.Scene;

namespace MapStoreViewer.Parsing;

/**
  * Reads compact WMO collision model files generated by the extractor.
  */
public static class VmapModelFileReader
{
    private const string Magic = "ESVMOD1";

    public static CollisionModelReadResult Read(string path, string modelKey)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentException.ThrowIfNullOrWhiteSpace(modelKey);

        using FileStream stream = File.OpenRead(path);
        using BinaryReader reader = new(stream);

        string magic = MapStoreBinaryPrimitives.ReadAscii(reader, Magic.Length, "vmap model magic");
        if (!string.Equals(magic, Magic, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{path} has invalid vmap model magic '{magic}'.");
        }

        uint version = reader.ReadUInt32();
        ushort build = reader.ReadUInt16();
        string normalizedPath = MapStoreBinaryPrimitives.ReadUtf8String(reader, path, "vmap model path");
        BoundsScene bounds = ReadBounds(reader);
        int groupCount = reader.ReadInt32();
        int vertexCount = reader.ReadInt32();
        int triangleCount = reader.ReadInt32();

        if (groupCount < 0 || vertexCount < 0 || triangleCount < 0)
        {
            throw new InvalidDataException($"{path} has invalid negative vmap model counts.");
        }

        List<CollisionGeometryGroupScene> groups = new(groupCount);
        for (int groupIndex = 0; groupIndex < groupCount; groupIndex++)
        {
            int storedGroupIndex = reader.ReadInt32();
            uint flags = reader.ReadUInt32();
            BoundsScene groupBounds = ReadBounds(reader);
            int groupVertexCount = reader.ReadInt32();
            int indexCount = reader.ReadInt32();

            if (groupVertexCount < 0 || indexCount < 0)
            {
                throw new InvalidDataException($"{path} has invalid negative group counts at group {groupIndex}.");
            }

            float[] vertices = new float[checked(groupVertexCount * 3)];
            for (int i = 0; i < vertices.Length; i++)
            {
                vertices[i] = reader.ReadSingle();
            }

            int[] indices = new int[indexCount];
            for (int i = 0; i < indices.Length; i++)
            {
                indices[i] = reader.ReadInt32();
            }

            groups.Add(new CollisionGeometryGroupScene(storedGroupIndex, flags, groupBounds, vertices, indices));
        }

        if (stream.Position != stream.Length)
        {
            throw new InvalidDataException($"{path} has {stream.Length - stream.Position} unread vmap model byte(s).");
        }

        CollisionModelScene model = new(modelKey, normalizedPath, build, version, bounds, groupCount, vertexCount, triangleCount, Loaded: true, Error: null);
        return new CollisionModelReadResult(model, groups);
    }

    private static BoundsScene ReadBounds(BinaryReader reader)
    {
        return new BoundsScene(ReadVector(reader), ReadVector(reader));
    }

    private static Vector3Scene ReadVector(BinaryReader reader)
    {
        return new Vector3Scene(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }
}

public sealed record CollisionModelReadResult(CollisionModelScene Model, IReadOnlyList<CollisionGeometryGroupScene> Groups);
